/* DATA TABLE */
export const DATA_TABLE_OPEN = "DATA_TABLE_OPEN";
export const DATA_TABLE_CLOSE = "DATA_TABLE_CLOSE";
export const DATA_TABLE_TOGGLE = "DATA_TABLE_TOGGLE";
export const DATA_TABLE_RESIZE = "DATA_TABLE_RESIZE";

/* USER INTERFACE */
export const SCREEN_RESIZE = "SCREEN_RESIZE";
export const LAYERS_PANEL_OPEN = "LAYERS_PANEL_OPEN";
export const LAYERS_PANEL_CLOSE = "LAYERS_PANEL_CLOSE";
export const RIGHT_PANEL_OPEN = "RIGHT_PANEL_OPEN";
export const RIGHT_PANEL_CLOSE = "RIGHT_PANEL_CLOSE";
