/* DATA TABLE */
export const DATA_TABLE_OPEN = "DATA_TABLE_OPEN";
export const DATA_TABLE_CLOSE = "DATA_TABLE_CLOSE";
export const DATA_TABLE_TOGGLE = "DATA_TABLE_TOGGLE";
export const DATA_TABLE_RESIZE = "DATA_TABLE_RESIZE";
export const DATA_TABLE_FETCH_DATA = "DATA_TABLE_FETCH_DATA";
export const DATA_TABLE_FETCH_DATA_SUCCESS = "DATA_TABLE_FETCH_DATA_SUCCESS";
export const DATA_TABLE_FETCH_DATA_FAIL = "DATA_TABLE_FETCH_DATA_FAIL";

/* USER INTERFACE */
export const SCREEN_RESIZE = "SCREEN_RESIZE";
export const LAYERS_PANEL_OPEN = "LAYERS_PANEL_OPEN";
export const LAYERS_PANEL_CLOSE = "LAYERS_PANEL_CLOSE";
export const RIGHT_PANEL_OPEN = "RIGHT_PANEL_OPEN";
export const RIGHT_PANEL_CLOSE = "RIGHT_PANEL_CLOSE";

/** INTERACTION */
export const SET_SELECTED_FEATURE = "SET_SELECTED_FEATURE";
export const CLEAR_SELECTED_FEATURE = "CLEAR_SELECTED_FEATURE";
